version: '3'

services:
  starry_te_pred:
    build: .
    volumes:
      - .:/code
    ports:
      - "8889:8888"
    command: jupyter-lab --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''